/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cartridgeinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cartridge info */
        get: operations["getCartridgeInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream a compressed image to the cartridge block device
         * @description Streams the request body into a pipeline equivalent to: gunzip | dd ...
         *
         *     The request body is expected to be a gzip-compressed disk image (e.g. .img.gz).
         *     The server will reject requests without Content-Length.
         */
        post: operations["flashCartridge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retropie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List RetroPie systems
         * @description Returns the list of RetroPie ROM system directories.
         *
         *     The server may mount the cartridge if needed.
         */
        get: operations["listRetroPieSystems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retropie/{system}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List games for a system
         * @description Lists files and directories under /home/pi/RetroPie/roms/{system}.
         *
         *     The server may mount the cartridge if needed.
         */
        get: operations["listRetroPieGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retropie/{system}/{game}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a game (file or zipped folder)
         * @description Downloads a ROM/game from a RetroPie cartridge.
         *
         *     - If {game} refers to a directory, the server will zip the directory and return the zip.
         *     - The response will include a Content-Disposition header so browsers download the file using a useful filename.
         *
         *     The server may mount the cartridge if needed.
         */
        get: operations["downloadRetroPieGame"];
        put?: never;
        /**
         * Upload a game
         * @description Uploads a ROM/game to /home/pi/RetroPie/roms/{system}/{game}.
         *
         *     Zip detection:
         *     - If {game} ends with .zip (case-insensitive), the server will treat the upload as a zip file and unpack it.
         *     - After unpacking, the zip file is deleted.
         *     - If the unpacked result contains a single top-level directory, its contents are moved up one level.
         *
         *     The server will reject requests without Content-Length.
         *     The server may mount the cartridge if needed.
         */
        post: operations["uploadRetroPieGame"];
        /**
         * Delete a game
         * @description Deletes a file or directory under /home/pi/RetroPie/roms/{system}/{game}.
         *
         *     The server may mount the cartridge if needed.
         */
        delete: operations["deleteRetroPieGame"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare cartridge for ejection
         * @description Prepares the cartridge for safe removal and triggers the UI to switch to the ejection screen.
         */
        post: operations["ejectCartridge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CartridgeInfo: {
            present: boolean;
            mounted: boolean;
            isRetroPie: boolean;
            /** @description RetroPie ROM system directories (null if not a RetroPie cartridge) */
            systems: string[] | null;
            busy: boolean;
        };
        Ok: {
            ok: boolean;
        };
        Error: {
            /** @description Short stable error code */
            error: string;
            /** @description Human-readable error message */
            message: string;
        };
        /**
         * Format: binary
         * @description Arbitrary bytes. This schema is used for streaming uploads/downloads.
         */
        ByteStream: string;
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict / invalid state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Content-Length required */
        LengthRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "length_required",
                 *       "message": "Content-Length header is required"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description RetroPie system directory name
         * @example snes
         */
        System: string;
        /**
         * @description Game file or directory name
         * @example mario.zip
         */
        Game: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCartridgeInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cartridge info snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartridgeInfo"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    flashCartridge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/gzip": components["schemas"]["ByteStream"];
                "application/octet-stream": components["schemas"]["ByteStream"];
            };
        };
        responses: {
            /** @description Flash started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            411: components["responses"]["LengthRequired"];
            500: components["responses"]["InternalError"];
        };
    };
    listRetroPieSystems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Systems list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listRetroPieGames: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description RetroPie system directory name
                 * @example snes
                 */
                system: components["parameters"]["System"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Games list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    downloadRetroPieGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description RetroPie system directory name
                 * @example snes
                 */
                system: components["parameters"]["System"];
                /**
                 * @description Game file or directory name
                 * @example mario.zip
                 */
                game: components["parameters"]["Game"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested game bytes */
            200: {
                headers: {
                    /**
                     * @description Attachment with a useful filename
                     * @example attachment; filename="mario.zip"
                     */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": components["schemas"]["ByteStream"];
                    "application/zip": components["schemas"]["ByteStream"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    uploadRetroPieGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description RetroPie system directory name
                 * @example snes
                 */
                system: components["parameters"]["System"];
                /**
                 * @description Game file or directory name
                 * @example mario.zip
                 */
                game: components["parameters"]["Game"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": components["schemas"]["ByteStream"];
            };
        };
        responses: {
            /** @description Upload completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            411: components["responses"]["LengthRequired"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteRetroPieGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description RetroPie system directory name
                 * @example snes
                 */
                system: components["parameters"]["System"];
                /**
                 * @description Game file or directory name
                 * @example mario.zip
                 */
                game: components["parameters"]["Game"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    ejectCartridge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ejection initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
}
